In [1]:
'''
1.
    create a packagenamed 'cricket' which will contain modules named batsman and bowler. 
create functions in respective modules. import the package and call all these functions 
in your program batsman: find average(runs,matches),strikerate(runs,balls)bowler:
find avg(runs,wickets),economyrate(overs,runs).
''';

from cricket import batsman , bowler

print('for batsman')
runs = int(input('enter runs:'))
matches = int(input('enter matches:'))
balls = int(input('enter balls:'))
print('batsman average:' , batsman.findaverage(runs,matches))
print('batsman strikerate:' , batsman.strikerate(runs,balls))
print('')

print('for bowler')
runs = int(input('enter runs:'))
wicket = int(input('enter wicket:'))
overs = int(input('enter overs:'))
print('bowler average:', bowler.findavg(runs,wickets))
print('batsman economyrate:', bowler.economyrate(overs,runs))

ModuleNotFoundError: No module named 'cricket'

In [3]:
'''
2.
  write a python function to find whether the number if prime or not
defbis prime(num)
''';

import math
def isPrime(num):
    if num<=1:
        return False
    for i in range(2,int(math.sqrt(num))+1):
        if num % i == 0:
            return False
    return True
num = int(input('enter a number:'))
print(isPrime(num))

enter a number: 7


True


In [4]:
'''
3.
  write a function is_palindrome(string)that takes a string as input and returns
true if string reads the same backward as forward(eg..,"racecar" is a palindrome)
''';

str=input('enter a string:')
def is_palindrome(string):
    rev=string[::-1]
    if rev==string:
        return True
    else:
        return False
        
is_palindrome(str)

enter a string: 4


True

In [12]:
'''
4.
   write a function reverse_list(data)that takes a list as input and returns
 new a list with the elements in reverse order (eg,.reverse_list([1,2,3])returns([3,2,1]).
''';
def reverse_list(data):
    return data[::-1]

print(reverse_list([1, 2, 3]))
print(reverse_list(['a', 'b', 'c']))

[3, 2, 1]
['c', 'b', 'a']


In [14]:
'''
5.
   write a function write_file(filename,content) that takes a filename and content as 
input and writes the content to the specified file.
''';
content = input('enter your content:')
def write_file(filename, content):
    with open(filename, 'w') as f:
        f.write(content)
        print('content has been written!!!')
write_file('example.txt',content)

 your content: 57


content has been written!!!


In [22]:
'''
6.
   write a function copy_file(source_filename,destination_filename) that takes the source and
destination filnames as input and copies the content of the source file to the
destination file.handle cases where the source file doesn't exist.
''';
def copy_file(source_filename,destination_filename):
    with open('source.txt','r') as s,open('destination.txt','w') as d:
        for line in s:
            d.write(line)

copy_file('source.txt','destination.txt')

In [16]:
'''
7.
   implement a function to calculate the dot product of two numpy arrays.
''';
import numpy as np
def calculate_dot_product(arr1, arr2):
    return(arr1*arr2)
arr1=np.array([[1,4,6],[5,1,78],[23,56,90]])
arr2=np.array([[23,34,45],[45,56,67],[2,9,4]])
result=calculate_dot_product(arr1,arr2)
print(result)

[[  23  136  270]
 [ 225   56 5226]
 [  46  504  360]]


In [15]:
'''
8.
   impement a GUI with a radio button selection for choosing a favorite color(eg.. red,green,blue)
change the background color of the window based on the selected radio button
''';
import tkinter as tk
from tkinter import ttk
def change_color():
    selected_color = color_var.get()
    top.configure(bg=selected_color)

top=tk.Tk()
top.title('background color')
top.geometry('550x400')

color_var=tk.StringVar()
colors=['red','green','blue','lavender','skyblue','pink','black']
for color in colors:
    radio_button=ttk.Radiobutton(top,text=color,value=color,variable=color_var,
                                command=change_color)
    radio_button.pack(anchor=tk.W)

top.mainloop()

In [2]:
'''
9.
   design a currency converter GUI. allow users to enter an amount and select the
currencies they want to convert between(eg..USD,EUR).display the converted 
amount in the selected currency.
''';

import tkinter as tk
from tkinter import ttk, messagebox
import requests

class CurrencyConverter(tk.Tk):
    def __init__(self):
        super().__init__()
    
        self.title("Currency Converter")
        self.geometry("400x200")

        self.amount_label = tk.Label(self,text="Amount:")
        self.amount_label.grid(row=0,column=0,padx=10,pady=10)

        self.amount_entry = tk.Entry(self)
        self.amount_entry.grid(row=0,column=1,padx=10,pady=10)

        self.from_currency_label = tk.Label(self,text="From:")
        self.from_currency_label.grid(row=1,column=0,padx=10,pady=10)

        self.from_currency_Combobox = ttk.Combobox(self,values=self.get_currency_list())
        self.from_currency_Combobox.grid(row=1,column=1,padx=10,pady=10)

        self.to_currency_label = tk.label(self,text="To:")
        self.to_currency_label.grid(row=2,column=0,padx=10,pady=10)

        self.to_currency_Combobox = ttk.Combobox(self,values=self.get_currency_list())
        self.to_currency_Combobox.grid(row=2,column=1,padx=10,pady=10)

        self.convert_button = tk.Button(self,text="convert",command=self.convert_currency)
        self.convert_button.grid(row=3,column=1,padx=10,pady=10)
                                
        self.result_label = tk.Label(self,text="converted Amount:")
        self.result_label.grid(row=4,column=0,padx=10,pady=10)

        self.result_value = tk.Label(self,text=" ")
        self.result_value.grid(row=4,column=1,padx=10,pady=10)

    def get_currency_list(self):
        response = requests.get('https://api.exchangerate-api.com/v4/latest/USD')
        if response.status_code == 200:
            data = response.json()
            return list(data['rates'].keys())
        else:
            messagebox.showerror("Error","Failed to fetch currency list")
            return[]

    def convert_currency(self):
        try:
            amount = float(self.amount_entry.get())
            from_currency = self.from_currency_combobox.get()
            to_currency = self.to_currency_combobox.get()
 
            response = requests.get(f'https://api.exchangerate-api.com/v4/latest/{from_currency}')
            if response.status_code == 200:
                data = response.json()
                rate = data['rates'][to_currency]
                converted_amount = amount * rate
                self.result_value.config(text=f"{converted_amount:2f}")
            else:
                 messagebox.showerror("Error","Failed to fetch conversion rate")
        except ValueError:
             messagebox.showerror("Error","invalid amount entered")
        except Exception as e:
             messagebox.showerror("Error",str(e))

if __name__ == "__main__":
    app = CurrencyConverter()
    app.mainloop()

ConnectionError: HTTPSConnectionPool(host='api.exchangerate-api.com', port=443): Max retries exceeded with url: /v4/latest/USD (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000153A2BB0090>: Failed to resolve 'api.exchangerate-api.com' ([Errno 11001] getaddrinfo failed)"))