In [1]:
import numpy as np

In [14]:
arr = np.array([12,23,45,56,32])

In [15]:
arr

array([12, 23, 45, 56, 32])

In [16]:
print(arr)

[12 23 45 56 32]


In [17]:
type(arr)

numpy.ndarray

In [18]:
arr.dtype

dtype('int32')

In [9]:
arr = np.array([12,23,45,56,32,66.32])

In [10]:
arr.dtype

dtype('float64')

In [19]:
arr

array([12, 23, 45, 56, 32])

In [21]:
arr = np.array (['12' ,'23' ,'45' ,'56' ,'32' ,'66.32','pune'], dtype='<U32')

In [22]:
arr

array(['12', '23', '45', '56', '32', '66.32', 'pune'], dtype='<U32')

In [23]:
%%timeit
arr = np.array([12, 23, 34, 45, 56, 32, 66.32, 'pune'])

6.55 µs ± 86.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
arr[3]

'56'

In [25]:
arr.shape

(7,)

In [32]:
arr = np.array([12,23,45,56,32,32])

In [33]:
arr * 2

array([ 24,  46,  90, 112,  64,  64])

In [35]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [38]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
#2d

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [50]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arr1.shape

(4, 3)

In [46]:
arr1.ndim

2

In [47]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr1.size

12

In [55]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [56]:
arr1.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [57]:
arr1.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [58]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [59]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [60]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
arr1[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [62]:
arr

array([12, 23, 45, 56, 32, 32])

In [63]:
arr.mean()

33.333333333333336

In [64]:
arr.min()

12

In [65]:
arr = np.array([1,2,3,4,5,6,7,1])

In [66]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.linalg.det(arr1)

-9.51619735392994e-16

In [74]:
np.linalg.inv(arr1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [77]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr1 @arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [79]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])